var car1 = "sabaru";
console.log(car1 == "sabaru" ? true : false);
var car2 = "honda";
console.log(car2 == "sabaru" ? true : false);
var bike1 = "Super star";
console.log(bike1 == "unique" ? true : false);
var bike2 = "unique";
console.log(bike2 == "unique" ? true : false);
var flower1 = "rose";
console.log(flower1 == "rose" ? true : false);
var flower2 = "sunflower";
console.log(flower2 == "rose" ? true : false);
var mobile1 = "Infinix";
console.log(mobile1 == "Infinix" ? true : false);
var mobile2 = "Apple";
console.log(mobile2 == "Infinix" ? true : false);
var watch1 = "rolex";
console.log(watch1 == "rolex" ? true : false);
var watch2 = "rolex";
console.log(watch2 == "apple watch" ? true : false);
